name: 'Setup Environment'
description: 'Sets up the CI environment with system dependencies and configurations'
runs:
  using: "composite"
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        # Show initial disk usage
        echo "=== Initial Disk Usage ==="
        df -h
        
        # Remove unnecessary software
        echo "=== Removing unnecessary packages ==="
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/swift
        sudo rm -rf /opt/hostedtoolcache
        
        # Clean apt cache
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        
        # Show final disk usage
        echo "=== Disk Usage After Cleanup ==="
        df -h

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential lld dbus-x11 gnome-keyring
      continue-on-error: true

    - name: Setup DBus and gnome-keyring
      shell: bash
      run: |
        # Start DBus session
        export $(dbus-launch)
        echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> $GITHUB_ENV
        
        # Create keyring directory
        mkdir -p ~/.local/share/keyrings
        
        # Start gnome-keyring daemon and unlock it
        eval $(echo -n "test" | gnome-keyring-daemon --unlock --components=secrets)
        
        # Export keyring control socket if set
        if [ -n "$GNOME_KEYRING_CONTROL" ]; then
          echo "GNOME_KEYRING_CONTROL=$GNOME_KEYRING_CONTROL" >> $GITHUB_ENV
        fi
