# Kong API Gateway Configuration for Local Supabase
# NOTE: PostgREST has been removed as we now use the official Supabase Storage API
_format_version: "3.0"

# Services and Routes
services:
  # PostgREST API - DEPRECATED: No longer used, keeping for reference
  # - name: rest-service
  #   url: http://rest:3000
  #   routes:
  #     - name: rest-route
  #       strip_path: true
  #       paths:
  #         - "/rest/v1"
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Authorization
                - Content-Type
                - X-Client-Info
                - apikey
                - x-supabase-api-version
              exposed_headers:
                - X-Total-Count
              credentials: true
              max_age: 3600
          exposed_headers:
            - X-Total-Count
          credentials: true
          max_age: 3600

  # Supabase Auth
  - name: auth
    url: http://auth:9999
    routes:
      - name: auth
        strip_path: true
        paths:
          - "/auth/v1/"
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Client-Info
            - apikey
          credentials: true
          max_age: 3600

  # Supabase Storage
  - name: storage
    url: http://storage:5000
    routes:
      - name: storage
        strip_path: true
        paths:
          - "/storage/v1/"
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Client-Info
            - apikey
            - cache-control
            - x-upsert
          credentials: true
          max_age: 3600

  # PostgreSQL Meta API
  - name: meta
    url: http://meta:8080
    routes:
      - name: meta
        strip_path: true
        paths:
          - "/pg/"

# Global plugins
plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Client-Info
        - apikey
        - x-supabase-api-version
      credentials: true
      max_age: 3600
