[build]
# Enable all features by default for development
# This helps catch compilation issues early
# all-features = true

[target.'cfg(target_os = "linux")']
# Use faster linker on Linux only
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
# Use the system linker on macOS
# No additional flags needed, will use default system linker

[target.x86_64-apple-darwin]
# Use the system linker on macOS
# No additional flags needed, will use default system linker

[alias]
# Useful cargo aliases
check-all = "check --all-targets --all-features"
test-all = "test --all-features --workspace"
build-all = "build --all-targets --all-features"
fmt-check = "fmt --all -- --check"
clippy-all = "clippy --all-targets --all-features -- -D warnings"

# Coverage aliases
cov = "llvm-cov --all-features --workspace --lcov --output-path lcov.info"
cov-html = "llvm-cov --all-features --workspace --html"
