# Documentation Configuration
# This file centralizes all documentation metadata and ensures consistency

project:
  name: "P2P AI Agents"
  version: "0.1.0"
  last_updated: "2025-06-14"
  status: "In Development"
  license: "MIT"
  rust_version: "1.75.0"

# Centralized terminology to ensure consistency
terminology:
  project_name: "P2P AI Agents"
  short_name: "p2p-ai-agents"
  network_protocol: "Network Protocol"
  network_implementation: "Network Implementation"
  task_processing: "Task Processing"
  task_management: "Task Management"

# Standard document structure template
document_structure:
  required_sections:
    - "Version Information"
    - "Table of Contents"
    - "Overview"
    - "Implementation Details"
    - "Security Considerations"
    - "Performance Characteristics"
    - "Testing"
    - "Related Documentation"

# Link validation and path resolution
paths:
  docs_root: "/workspaces/p2p-ai-agents/docs"
  implementation: "implementation"
  architecture: "architecture"
  development: "development"
  user_guides: "user-guides"

# Cross-reference validation
references:
  agent_implementation: "implementation/agent.md"
  security_implementation: "architecture/security.md"
  development_setup: "development/README.md"
  monitoring_guide: "user-guides/troubleshooting.md"

# Version tracking for each document category
versions:
  architecture: "0.1.0"
  implementation: "0.1.0"
  development: "0.1.0"
  user_guides: "0.1.0"
